DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMERO_MATRICULA VARCHAR(10) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL);

INSERT INTO ODONTOLOGOS VALUES(DEFAULT,'45566','JUAN','PEREZ');
INSERT INTO ODONTOLOGOS VALUES(DEFAULT,'1234','MARIA','CRUZ');